In [5]:
from utils.ipc import ParameterEstimatorIPC

estimator = ParameterEstimatorIPC(executable_path="./estimation-engine/forward-algorithm/x64/Release/forward-algorithm.exe")

print(estimator.estimate([0.2, 0.5,0.8,0.8,0.9]))

[0.306306, 0.728642, 0.0655868, -3.30044, 0.109519, 0.698508]

In [ ]:
from utils.ipc import VaRCalculatorIPC, ModelParameters
import random

calc = VaRCalculatorIPC(executable_path="./estimation-engine/forward-algorithm/x64/Release/VaR-calculation.exe")

nums = [random.uniform(-0.05, 0.05) for _ in range(100)]  # Generate 100 random numbers between -0.05 and 0.05
VaR = calc.calculate_var(nums)

VaR

([-1.56342,
  -1.48772,
  -1.43023,
  -1.38765,
  -1.35731,
  -1.33881,
  -1.32334,
  -1.31869,
  -1.30921,
  -1.30763,
  -1.30561,
  -1.30313,
  -1.2984,
  -1.30172,
  -1.3004,
  -1.30117,
  -1.29694,
  -1.29828,
  -1.29825,
  -1.29817,
  -1.29622,
  -1.2992,
  -1.29802,
  -1.29934,
  -1.29858,
  -1.29731,
  -1.29571,
  -1.298,
  -1.29623,
  -1.30055,
  -1.29948,
  -1.29656,
  -1.29596,
  -1.29596,
  -1.29621,
  -1.29923,
  -1.29967,
  -1.29663,
  -1.29686,
  -1.29925,
  -1.29905,
  -1.29776,
  -1.30036,
  -1.29724,
  -1.29816,
  -1.30004,
  -1.29821,
  -1.29984,
  -1.29695,
  -1.30022,
  -1.29853,
  -1.29593,
  -1.299,
  -1.29751,
  -1.2965,
  -1.30013,
  -1.29978,
  -1.29804,
  -1.29901,
  -1.29813,
  -1.29961,
  -1.29883,
  -1.29644,
  -1.29821,
  -1.29724,
  -1.29931,
  -1.29792,
  -1.29938,
  -1.29571,
  -1.29834,
  -1.29573,
  -1.29611,
  -1.2959,
  -1.29784,
  -1.30059,
  -1.30018,
  -1.30052,
  -1.29793,
  -1.30042,
  -1.29604,
  -1.30047,
  -1.29774,
  -1.29616,
  -1.29771,
  -1.29934,
  -1.29995,
  -1.2982,
  -1.2982,
  -1.29764,
  -1.29608,
  -1.30002,
  -1.30022,
  -1.30077,
  -1.29935,
  -1.29944,
  -1.29674,
  -1.29825,
  -1.3003,
  -1.29724,
  -1.29673],
 '')

In [2]:
from datalink.scraper import TGJUScraper

scraper = TGJUScraper(headless=True, max_pages=2)
df = scraper.scrape()

df

2026-08-06 09:28:06,399 - INFO - Initializing resilient Firefox WebDriver...
2026-08-06 09:28:06,402 - INFO - ====== WebDriver manager ======
2026-08-06 09:28:07,496 - INFO - Driver [C:\Users\CHAMPION\.wdm\drivers\geckodriver\win64\v0.37.1\geckodriver.exe] found in cache by browser version
2026-08-06 09:28:13,024 - INFO - Navigating to https://www.tgju.org/profile/tgju_gold_irg18/history
2026-08-06 09:28:15,670 - INFO - Scraping page 1/2...
2026-08-06 09:28:17,543 - INFO - Scraping page 2/2...
2026-08-06 09:28:17,566 - INFO - Closing Web Browser...
2026-08-06 09:29:21,105 - INFO - Successfully scraped 60 total records.
2026-08-06 09:29:21,108 - INFO - Data cached to: D:\Source\svm-using-hmm\datalink\cache\gold18_history.csv

,Reopened,Lowest,Highest,Final,Change_Amount,Change_Percent,Date_Miladi,Date_Jalali
0,"183,221,000","183,201,000","197,711,000","197,631,000",10000,0.01%,2026/08/05,1405/05/14
1,"197,621,000","182,151,000","197,711,000","197,621,000",10000,0.01%,2026/08/04,1405/05/13
2,"197,621,000","183,281,000","197,711,000","197,631,000",50000,0.03%,2026/08/03,1405/05/12
3,"197,701,000","183,061,000","197,711,000","197,681,000",10020000,5.34%,2026/08/02,1405/05/11
4,"197,691,000","186,291,000","197,711,000","187,661,000",9970000,5.31%,2026/08/01,1405/05/10
5,"197,681,000","186,141,000","197,711,000","197,631,000",70000,0.04%,2026/07/31,1405/05/09
6,"197,681,000","186,591,000","197,711,000","197,701,000",70000,0.04%,2026/07/30,1405/05/08
7,"197,621,000","183,831,000","197,711,000","197,631,000",10000,0.01%,2026/07/29,1405/05/07
8,"197,621,000","182,951,000","197,711,000","197,621,000",60000,0.03%,2026/07/28,1405/05/06
9,"197,631,000","181,591,000","197,711,000","197,681,000",60000,0.03%,2026/07/27,1405/05/05
10,"181,561,000","178,931,000","197,711,000","197,621,000",10000,0.01%,2026/07/26,1405/05/04
11,"197,631,000","181,391,000","197,711,000","197,631,000",20000,0.01%,2026/07/25,1405/05/03
12,"197,631,000","187,001,000","197,711,000","197,651,000",30000,0.02%,2026/07/24,1405/05/02
13,"197,621,000","187,731,000","197,711,000","197,621,000",50000,0.03%,2026/07/23,1405/05/01
14,"197,661,000","184,391,000","197,711,000","197,671,000",30000,0.02%,2026/07/22,1405/04/31
15,"197,671,000","182,721,000","197,711,000","197,701,000",70000,0.04%,2026/07/21,1405/04/30
16,"197,631,000","181,161,000","197,711,000","197,631,000",70000,0.04%,2026/07/20,1405/04/29
17,"189,961,000","186,551,000","197,711,000","197,701,000",80000,0.04%,2026/07/19,1405/04/28
18,"197,621,000","184,821,000","197,711,000","197,621,000",50000,0.03%,2026/07/18,1405/04/27
19,"197,711,000","182,961,000","197,711,000","197,671,000",50000,0.03%,2026/07/17,1405/04/26
20,"197,631,000","182,261,000","197,711,000","197,621,000",70000,0.04%,2026/07/16,1405/04/25
21,"197,691,000","178,691,000","197,711,000","197,691,000",10000,0.01%,2026/07/15,1405/04/24
22,"197,631,000","176,461,000","197,711,000","197,701,000",21190000,12%,2026/07/14,1405/04/23
23,"197,691,000","175,651,000","197,711,000","176,511,000",21160000,11.99%,2026/07/13,1405/04/22
24,"197,651,000","175,561,000","197,711,000","197,671,000",22040000,12.55%,2026/07/12,1405/04/21
25,"197,621,000","175,181,000","197,711,000","175,631,000",1400000,0.8%,2026/07/11,1405/04/20
26,"197,691,000","176,561,000","197,711,000","177,031,000",20600000,11.64%,2026/07/10,1405/04/19
27,"197,651,000","178,491,000","197,711,000","197,631,000",19050000,10.67%,2026/07/09,1405/04/18
28,"197,701,000","177,191,000","197,711,000","178,581,000",19050000,10.67%,2026/07/08,1405/04/17
29,"177,431,000","176,301,000","197,711,000","197,631,000",19050000,10.67%,2026/07/07,1405/04/16
30,"197,711,000","177,281,000","197,711,000","197,631,000",19850000,11.17%,2026/07/06,1405/04/15
31,"197,631,000","176,431,000","197,711,000","177,781,000",19850000,11.17%,2026/07/05,1405/04/14
32,"197,621,000","176,351,000","197,711,000","197,631,000",19390000,10.88%,2026/07/04,1405/04/13
33,"197,631,000","176,111,000","197,711,000","178,241,000",19440000,10.91%,2026/07/03,1405/04/12
34,"197,631,000","171,241,000","197,711,000","197,681,000",25970000,15.12%,2026/07/02,1405/04/11
35,"169,451,000","169,201,000","197,711,000","171,711,000",25920000,15.1%,2026/07/01,1405/04/10
36,"197,631,000","167,711,000","197,711,000","197,631,000",60000,0.03%,2026/06/30,1405/04/09
37,"197,691,000","167,641,000","197,711,000","197,691,000",10000,0.01%,2026/06/29,1405/04/08
38,"165,041,000","164,951,000","197,711,000","197,701,000",32720000,19.83%,2026/06/28,1405/04/07
39,"162,731,000","162,651,000","165,501,000","164,981,000",2260000,1.39%,2026/06/27,1405/04/06
40,"162,371,000","162,081,000","162,981,000","162,721,000",250000,0.15%,2026/06/26,1405/04/05
41,"161,681,000","161,501,000","162,501,000","162,471,000",820000,0.51%,2026/06/25,1405/04/04
42,"161,481,000","161,171,000","163,111,000","161,651,000",160000,0.1%,2026/06/24,1405/04/03
43,"160,931,000","160,091,000","161,871,000","161,811,000",980000,0.61%,2026/06/23,1405/04/02
44,"161,841,000","160,151,000","162,121,000","160,831,000",1100000,0.68%,2026/06/22,1405/04/01
45,"162,481,000","159,741,000","162,841,000","161,931,000",470000,0.29%,2026/06/21,1405/03/31
46,"161,401,000","161,331,000","164,851,000","162,401,000",1050000,0.65%,2026/06/20,1405/03/30
47,"159,091,000","158,841,000","162,091,000","161,351,000",2340000,1.47%,2026/06/19,1405/03/29
48,"164,161,000","158,801,000","164,171,000","159,011,000",5070000,3.19%,2026/06/18,1405/03/28
49,"158,611,000","156,621,000","164,251,000","164,081,000",5400000,3.4%,2026/06/17,1405/03/27
50,"163,981,000","154,771,000","164,671,000","158,681,000",5740000,3.62%,2026/06/16,1405/03/26
51,"175,251,000","163,701,000","197,711,000","164,421,000",10910000,6.64%,2026/06/15,1405/03/25
52,"197,681,000","171,401,000","197,711,000","175,331,000",22290000,12.71%,2026/06/14,1405/03/24
53,"197,621,000","171,381,000","197,711,000","197,621,000",21700000,12.34%,2026/06/13,1405/03/23
54,"180,491,000","175,711,000","197,711,000","175,921,000",21700000,12.34%,2026/06/12,1405/03/22
55,"197,621,000","179,311,000","197,711,000","197,621,000",50000,0.03%,2026/06/11,1405/03/21
56,"197,671,000","179,131,000","197,711,000","197,671,000",40000,0.02%,2026/06/10,1405/03/20
57,"197,631,000","180,221,000","197,711,000","197,711,000",20000,0.01%,2026/06/09,1405/03/19
58,"197,631,000","180,491,000","197,711,000","197,691,000",20000,0.01%,2026/06/08,1405/03/18
59,"197,661,000","181,451,000","197,711,000","197,711,000",80000,0.04%,2026/06/07,1405/03/17

In [ ]:
from datalink.processor import calculate_tgju_log_returns
from datalink.scraper import TGJUScraper

scraper = TGJUScraper(headless=True, max_pages=2)
data = scraper.load_data().pipe(calculate_tgju_log_returns)

data

2026-08-06 09:51:56,484 - INFO - Reading cached data from D:\Source\svm-using-hmm\datalink\cache\gold18_history.csv

0           NaN
1     -0.005060
2      0.005060
3      0.025296
4     -5.201748
5      5.176451
6      0.035413
7     -0.035413
8     -0.005060
9      0.030357
10    -0.030357
11     0.005060
12     0.010119
13    -0.015179
14     0.025298
15     0.015176
16    -0.035413
17     0.035413
18    -0.040473
19     0.025298
20    -0.025298
21     0.035415
22     0.005058
23   -11.337259
24    11.322084
25   -11.821883
26     0.793966
27    11.007680
28   -10.135938
29    10.135938
30     0.000000
31   -10.584920
32    10.584920
33   -10.326509
34    10.351805
35   -14.084179
36    14.058882
37     0.030355
38     0.005058
39   -18.092547
40    -1.379324
41    -0.153755
42    -0.505983
43     0.098930
44    -0.607486
45     0.681619
46     0.289827
47    -0.648647
48    -1.460873
49     3.138683
50    -3.346431
51     3.553431
52     6.424540
53    11.967544
54   -11.631602
55    11.631602
56     0.025298
57     0.020234
58    -0.010116
59     0.010116
Name: Log_Return, dtype: float64

In [1]:
from datalink.simulator import generate_synthetic_log_returns
from utils.datastructs import ModelParameters

y = generate_synthetic_log_returns(ModelParameters(), 0)

y

     Log_Return
0      0.000000
1     -0.951000
2      0.158125
3     -2.133294
4     -1.129234
..          ...
296    3.368375
297    0.021018
298    0.222547
299    5.931681
300    0.628963

[301 rows x 1 columns]